config/routes.rb
Dgt::Application.routes.draw do
  resources :cars

  root :to => 'cars#index'

end

app/models/car.rb
class Car < ActiveRecord::Base

  #TODO This should go on its own Model class
  EU_COUNTRIES=["Austria","Belgium","Bulgaria","Croatia","Cyprus","Czech Republic","Denmark","Estonia","Finland","France","Germany","Greece","Hungary","Ireland","Italy","Latvia","Lithuania","Luxembourg","Malta","Netherlands","Poland","Portugal","Romania","Slovakia","Slovenia","Spain","Sweden","United Kingdom"]
  
  attr_accessible :brand, :country, :horsepower, :model, :number_plate, :owner, :register_date
  
  validates_presence_of :brand, :country, :horsepower, :model, :number_plate, :owner, :register_date
  
  validates_inclusion_of :country, :in => EU_COUNTRIES,
                    :message => 'is not an EU country'

  validates_format_of :number_plate, :with => /\d{4}\-[A-Z]{3}/,
                     :message => 'does not look like a standard plate number (1234-ABC) mind the capital letters'
  
  MAX_CAR_AGE = 30
  validates_inclusion_of :register_date, :in => Date.civil((Date.today.year - MAX_CAR_AGE),1,1) .. Date.today,
                     :message => "is older than #{MAX_CAR_AGE} years, hence it must follow an special procedure"


  validates_numericality_of :horsepower

  validates_uniqueness_of :number_plate, :case_sensitive => false,
                         :message => 'has already been registered'
  
  def available_countries
    EU_COUNTRIES
  end

  def max_car_age
    MAX_CAR_AGE
  end

end

app/models/entry.rb
class Entry < ActiveRecord::Base
  # attr_accessible :title, :body
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/cars_controller.rb
class CarsController < ApplicationController
  # GET /cars
  # GET /cars.json
  def index
    if params[:number_plate]
      @cars = Car.where(number_plate: params[:number_plate])
    else
      @cars = Car.all
    end
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @cars }
    end
  end

  # GET /cars/1
  # GET /cars/1.json
  def show
    @car = Car.find(params[:id])
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @car }
    end
  end

  # GET /cars/new
  # GET /cars/new.json
  def new
    @car = Car.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @car }
    end
  end

  # GET /cars/1/edit
  def edit
    @car = Car.find(params[:id])
  end

  # POST /cars
  # POST /cars.json
  def create
    @car = Car.new(params[:car])

    respond_to do |format|
      if @car.save
        format.html { redirect_to @car, notice: 'Car was successfully created.' }
        format.json { render json: @car, status: :created, location: @car }
      else
        format.html { render action: "new" }
        format.json { render json: @car.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /cars/1
  # PUT /cars/1.json
  def update
    @car = Car.find(params[:id])

    respond_to do |format|
      if @car.update_attributes(params[:car])
        format.html { redirect_to @car, notice: 'Car was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @car.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cars/1
  # DELETE /cars/1.json
  def destroy
    @car = Car.find(params[:id])
    @car.destroy

    respond_to do |format|
      format.html { redirect_to cars_url }
      format.json { head :no_content }
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cars_helper.rb
module CarsHelper
end

app/views/cars/_form.html.erb
<%= form_for(@car) do |f| %>
  <% if @car.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@car.errors.count, "error") %> prohibited this car from being saved:</h2>

      <ul>
      <% @car.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :brand %><br />
    <%= f.text_field :brand %>
  </div>
  <div class="field">
    <%= f.label :model %><br />
    <%= f.text_field :model %>
  </div>
  <div class="field">
    <%= f.label :horsepower %><br />
    <%= f.text_field :horsepower %>
  </div>
  <div class="field">
    <%= f.label :number_plate %><br />
    <%= f.text_field :number_plate %>
  </div>
  <div class="field">
    <%= f.label :register_date %><br />
    <%= f.date_select :register_date , :start_year => Date.today.year - @car.max_car_age, :end_year => Date.today.year %>
  </div>
  <div class="field">
    <%= f.label :country %><br />
    <%= f.select :country, @car.available_countries %>
  </div>
  <div class="field">
    <%= f.label :owner %><br />
    <%= f.text_field :owner %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/cars/edit.html.erb
<h1>Editing car</h1>

<%= render 'form' %>

<%= link_to 'Show', @car %> |
<%= link_to 'Back', cars_path %>

app/views/cars/index.html.erb
<h1>Listing cars</h1>

<table>
  <tr>
    <th>Brand</th>
    <th>Model</th>
    <th>Horsepower</th>
    <th>Number plate</th>
    <th>Register date</th>
    <th>Country</th>
    <th>Owner</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @cars.each do |car| %>
  <tr>
    <td><%= car.brand %></td>
    <td><%= car.model %></td>
    <td><%= car.horsepower %></td>
    <td><%= car.number_plate %></td>
    <td><%= car.register_date %></td>
    <td><%= car.country %></td>
    <td><%= car.owner %></td>
    <td><%= link_to 'Show', car %></td>
    <td><%= link_to 'Edit', edit_car_path(car) %></td>
    <td><%= link_to 'Destroy', car, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Car', new_car_path %>

app/views/cars/new.html.erb
<h1>New car</h1>

<%= render 'form' %>

<%= link_to 'Back', cars_path %>

app/views/cars/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Brand:</b>
  <%= @car.brand %>
</p>

<p>
  <b>Model:</b>
  <%= @car.model %>
</p>

<p>
  <b>Horsepower:</b>
  <%= @car.horsepower %>
</p>

<p>
  <b>Number plate:</b>
  <%= @car.number_plate %>
</p>

<p>
  <b>Register date:</b>
  <%= @car.register_date %>
</p>

<p>
  <b>Country:</b>
  <%= @car.country %>
</p>

<p>
  <b>Owner:</b>
  <%= @car.owner %>
</p>


<%= link_to 'Edit', edit_car_path(@car) %> |
<%= link_to 'Back', cars_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Dgt</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>